version: '3'
services:
    ##############################################
    # 画面側(フロントエンド)
    ##############################################
    udemy-frontend-next:
      container_name: udemy-frontend-next-app
      build:
          context: ./frontend/next
          dockerfile: Dockerfile.dev
      tty: true
      ports:
        - "3000:3000"
        - "3001:3001"
      volumes:
          - "./frontend/next:/usr/src/app/frontend"
      networks:
          aschat_network:
              ipv4_address: 192.168.144.11
    ##############################################
    # サービス側(バックエンド)
    ##############################################
    udemy-backend-django:
      container_name: udemy-backend-django-app
      build:
          context: ./backend/django
          dockerfile: Dockerfile.dev
      tty: true
      ports:
        - "8000:8000"
      volumes:
          - "./backend/django:/usr/src/app/backend"
      networks:
          aschat_network:
              ipv4_address: 192.168.144.21

networks:
    aschat_network:
        ipam:
            driver: default
            config:
                - subnet: 192.168.144.0/24