FROM python:3.9.7-slim-buster

WORKDIR /usr/src/app/backend

COPY /requirements-dev.txt ./

RUN pip install --upgrade pip && \
    pip install virtualenv

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m virtualenv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN . /opt/venv/bin/activate &&  \
    pip install -r requirements-dev.txt